export const OPEN_CHAT = "CHAT_OPEN";
export const CLOSE_CHAT = "CHAT_CLOSE";

export const GET_TABLES_START = "GET_TABLES_START";
export const GET_TABLES_ERROR = "GET_TABLES_ERROR";
export const GET_TABLES_COMPLETE = "GET_TABLES_COMPLETE";

export const GET_ROOMS_START = "GET_ROOMS_START";
export const GET_ROOMS_ERROR = "GET_ROOMS_ERROR";
export const GET_ROOMS_COMPLETE = "GET_ROOMS_COMPLETE";

export const GET_RANDOM_ROOM_START = "GET_RANDOM_ROOM_START";
export const GET_RANDOM_ROOM_ERROR = "GET_RANDOM_ROOM_ERROR";
export const GET_RANDOM_ROOM_COMPLETE = "GET_RANDOM_ROOM_COMPLETE";

export const SET_CURRENT_ROOM = "SET_CURRENT_ROOM";

export const SET_CURRENT_TABLE = "SET_CURRENT_TABLE";